import { Router, type IRouter } from "express";
import projectsRouter from "./projects";
import contractsRouter from "./contracts";
import contractorsRouter from "./contractors";
import documentsRouter from "./documents";
import meetingsRouter from "./meetings";
import lettersRouter from "./letters";
import dashboardRouter from "./dashboard";
import notificationsRouter from "./notifications";
import voiceRouter from "./voice";
import uploadRouter from "./upload";
import financeRouter from "./finance";
import globalRouter from "./global";
import contactsRouter from "./contacts";
import reportsRouter from "./reports";
import usersRouter from "./users";
import auditRouter from "./audit";
import photosRouter from "./photos";
import attachmentsRouter from "./attachments";
import categoriesRouter from "./categories";
import inviteRouter from "./invite";
import profilesRouter from "./profiles";
import emailArchiveRouter from "./emailArchive";
import messagesRouter from "./messages";
import hrEmployeesRouter from "./hr/employees";
import hrCandidatesRouter from "./hr/candidates";
import hrCorporateRouter from "./hr/corporate";
import hrFilesRouter from "./hr/files";
import { enforcePermissions } from "./permissions";
import { requireHrAccess } from "./hr/permissions";

const router: IRouter = Router();

router.use(enforcePermissions);
router.use(requireHrAccess);
router.use(hrFilesRouter);
router.use(hrEmployeesRouter);
router.use(hrCandidatesRouter);
router.use(hrCorporateRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(projectsRouter);
router.use(contractsRouter);
router.use(contractorsRouter);
router.use(documentsRouter);
router.use(meetingsRouter);
router.use(lettersRouter);
router.use(voiceRouter);
router.use(uploadRouter);
router.use(financeRouter);
router.use(globalRouter);
router.use(contactsRouter);
router.use(reportsRouter);
router.use(usersRouter);
router.use(auditRouter);
router.use(photosRouter);
router.use(attachmentsRouter);
router.use(categoriesRouter);
router.use(inviteRouter);
router.use(profilesRouter);
router.use(emailArchiveRouter);
router.use(messagesRouter);

export default router;
