import { createContext, useContext, useState, useEffect, useCallback } from "react";

export type Lang = "ar" | "en";

const T = {
  ar: {
    // Nav
    dashboard: "لوحة التحكم",
    projects: "المشاريع",
    contracts: "العقود",
    contractors: "المقاولون",
    meetings: "الاجتماعات",
    letters: "الخطابات والمراسلات",
    finance: "الأرشيف المالي",
    emailArchive: "أرشيف البريد",
    search: "البحث الموحد",
    notifications: "الإشعارات",
    reports: "التقارير",
    faq: "الأسئلة الشائعة",
    users: "المستخدمون",
    // App shell
    appName: "أرشيف ذكي",
    appSub: "نظام إدارة الأرشيف",
    system: "النظام",
    // Notifications panel
    alerts: "الإشعارات",
    markAllRead: "تحديد الكل مقروء",
    noNotifications: "لا توجد إشعارات",
    showAll: "عرض الكل",
    // Login
    welcome: "مرحباً بك",
    smartSystem: "نظام الأرشيف الذكي",
    loginTitle: "تسجيل الدخول",
    employee: "موظف",
    admin: "إداري",
    adminUsername: "اسم المستخدم",
    adminPassword: "كلمة المرور",
    emailField: "البريد الإلكتروني",
    passwordField: "كلمة المرور",
    loginBtn: "تسجيل الدخول",
    loggingIn: "جاري الدخول...",
    fillFields: "يرجى ملء جميع الحقول",
    errorOccurred: "حدث خطأ، يرجى المحاولة مجدداً",
    quickAdd: "إضافة جديد",
    logout: "خروج",
    // Dashboard
    dashboardSub: "نظرة عامة على جميع مشاريعك",
    docsAndRecords: "الوثائق والسجلات",
    recentProjects: "آخر المشاريع",
    viewAll: "عرض الكل",
    totalProjects: "إجمالي المشاريع",
    activeProjects: "مشاريع نشطة",
    completedProjects: "مشاريع مكتملة",
    onHoldProjects: "متوقفة",
    totalContracts: "العقود",
    totalDocuments: "المستندات",
    totalMeetings: "الاجتماعات",
    totalLetters: "الخطابات",
    // Projects page
    newProject: "مشروع جديد",
    searchProject: "بحث عن مشروع...",
    allStatuses: "كل الحالات",
    noProjects: "لا توجد مشاريع",
    noProjectsSub: "ابدأ بإضافة مشروعك الأول",
    addProject: "إضافة مشروع",
    edit: "تعديل",
    delete: "حذف",
    deleteProject: "حذف المشروع",
    deleteProjectMsg: "هل أنت متأكد من حذف هذا المشروع؟ سيتم حذف جميع البيانات المرتبطة به.",
    projectCreated: "تم إنشاء المشروع بنجاح",
    projectCreateFail: "فشل في إنشاء المشروع",
    projectUpdated: "تم تحديث المشروع",
    projectUpdateFail: "فشل في التحديث",
    projectDeleted: "تم حذف المشروع",
    projectDeleteFail: "فشل في الحذف",
    saving: "جاري الحفظ...",
    createProjectBtn: "إنشاء المشروع",
    saveEdits: "حفظ التعديلات",
    projectNameLabel: "اسم المشروع *",
    projectNamePlaceholder: "مثال: برج الأعمال المركزي",
    descLabel: "وصف المشروع",
    descPlaceholder: "وصف مختصر للمشروع...",
    clientLabel: "العميل *",
    clientPlaceholder: "اسم العميل أو الجهة",
    statusLabel: "الحالة",
    progressLabel: "نسبة الإنجاز",
    startDateLabel: "تاريخ البداية *",
    endDateLabel: "تاريخ الانتهاء",
    budgetLabel: "الميزانية (ريال)",
    locationLabel: "الموقع",
    locationPlaceholder: "المدينة، الحي",
    mapsLabel: "رابط الموقع في خرائط جوجل",
    // Contracts page
    contractsSub: "جميع العقود عبر المشاريع",
    addBtn: "إضافة",
    searchContract: "بحث عن عقد...",
    noContracts: "لا توجد عقود",
    noContractsSub: "أضف أول عقد بالضغط على الزر أعلاه",
    addContract: "إضافة عقد",
    contractAdding: "جاري الإضافة...",
    addContractBtn: "إضافة العقد",
    projectField: "المشروع *",
    chooseProject: "اختر المشروع",
    contractTitle: "عنوان العقد *",
    contractTitlePlaceholder: "عنوان العقد",
    contractParty: "الطرف الآخر *",
    contractPartyPlaceholder: "اسم الشركة أو المقاول",
    contractValue: "قيمة العقد (ر.س)",
    notes: "ملاحظات",
    // Contractors page
    contractorsSub: "جميع المقاولين عبر المشاريع",
    searchContractor: "بحث عن مقاول...",
    noContractors: "لا يوجد مقاولون",
    noContractorsSub: "أضف أول مقاول بالضغط على الزر أعلاه",
    addContractor: "إضافة مقاول",
    contractorName: "الاسم *",
    contractorNamePh: "اسم المقاول",
    specialty: "التخصص *",
    specialtyPh: "مهندس مدني، كهربائي...",
    phone: "الهاتف",
    email: "البريد",
    contractorAdding: "جاري الإضافة...",
    addContractorBtn: "إضافة المقاول",
    active: "نشط",
    inactive: "غير نشط",
    editRating: "تعديل التقييم",
    ratePerf: "تقييم الأداء",
    average: "المتوسط",
    workQuality: "جودة العمل",
    scheduleCompliance: "الالتزام بالمواعيد",
    safetyStandards: "معايير السلامة",
    executionSpeed: "سرعة التنفيذ",
    saveRating: "حفظ التقييم",
    cancelBtn: "إلغاء",
    // Meetings page
    meetingsSub: "جميع الاجتماعات عبر المشاريع",
    searchMeeting: "بحث عن اجتماع...",
    noMeetings: "لا توجد اجتماعات",
    noMeetingsSub: "أضف أول اجتماع بالضغط على الزر أعلاه",
    addMeeting: "إضافة اجتماع",
    meetingTitle: "موضوع الاجتماع *",
    meetingTitlePh: "موضوع الاجتماع",
    meetingDate: "التاريخ *",
    meetingLocation: "الموقع",
    meetingLocationPh: "قاعة الاجتماعات...",
    agenda: "جدول الأعمال",
    agendaPrefix: "جدول الأعمال:",
    attendees: "حاضرين",
    meetingAdding: "جاري الإضافة...",
    addMeetingBtn: "إضافة الاجتماع",
    // Letters page
    lettersSub: "جميع الخطابات الصادرة والواردة",
    searchLetter: "بحث عن خطاب...",
    noLetters: "لا توجد خطابات",
    noLettersSub: "أضف أول خطاب بالضغط على الزر أعلاه",
    addLetter: "إضافة خطاب",
    letterSubject: "الموضوع *",
    letterSubjectPh: "موضوع الخطاب",
    direction: "الاتجاه",
    outgoing: "صادر",
    incoming: "وارد",
    from: "من *",
    fromPh: "المرسل",
    to: "إلى *",
    toPh: "المستلم",
    refNum: "رقم المرجع",
    autoRefNote: "سيتم توليد رقم مرجعي تلقائي عند الحفظ",
    letterAdding: "جاري الإضافة...",
    addLetterBtn: "إضافة الخطاب",
    received: "تم الاستلام",
    sent: "تم الإرسال",
    notSent: "لم يُرسل",
    // Finance page
    financeSub: "سجل الإيرادات والمصروفات والتذكيرات المالية",
    totalIncome: "إجمالي الإيرادات",
    totalExpense: "إجمالي المصروفات",
    netBalance: "الرصيد الصافي",
    surplus: "فائض",
    deficit: "عجز",
    reminders30: "تذكيرات خلال 30 يوماً",
    reminder: "تذكير",
    all: "الكل",
    income: "الإيرادات",
    expense: "المصروفات",
    noFinance: "لا توجد سجلات",
    noFinanceSub: "أضف أول سجل مالي",
    financeAdded: "تم إضافة السجل المالي",
    financeAddFail: "فشل في الإضافة",
    financeUpdated: "تم تحديث السجل",
    financeUpdateFail: "فشل في التحديث",
    financeDeleted: "تم حذف السجل",
    financeDeleteFail: "فشل في الحذف",
    deleteFinance: "حذف السجل المالي",
    deleteFinanceMsg: "هل أنت متأكد من حذف هذا السجل المالي؟",
    addFinance: "إضافة سجل مالي",
    editFinance: "تعديل السجل المالي",
    incomeBtn: "إيراد +",
    expenseBtn: "مصروف −",
    financeTitle: "العنوان *",
    financeTitlePh: "مثال: دفعة مشروع برج الأعمال",
    amount: "المبلغ (ر.س) *",
    category: "الفئة",
    reminderDate: "تذكير بتاريخ",
    addFinanceBtn: "إضافة السجل",
    // Search page
    searchSub: "ابحث في جميع المشاريع والبيانات",
    searchPlaceholder: "ابحث عن أي شيء...",
    searchPrompt: "اكتب للبحث في المشاريع والمقاولين والعقود...",
    results: "نتيجة",
    noResults: "لا توجد نتائج",
    // Reports page
    reportsSub: "تقارير تفصيلية لكل مشروع على حدة",
    weekly: "أسبوعي",
    monthly: "شهري",
    exportPDF: "تصدير كـ PDF",
    noReports: "لا توجد مشاريع لعرض تقاريرها",
    progress: "إنجاز",
    // Users page
    usersSub: "إدارة الحسابات والصلاحيات وسجل التدقيق",
    usersTab: "المستخدمون",
    auditTab: "سجل التدقيق",
    adminOnly: "هذه الصفحة مخصصة للمدير فقط",
    noAudit: "لا توجد سجلات تدقيق بعد",
    changeRole: "تغيير",
    save: "حفظ",
  },
  en: {
    // Nav
    dashboard: "Dashboard",
    projects: "Projects",
    contracts: "Contracts",
    contractors: "Contractors",
    meetings: "Meetings",
    letters: "Letters & Correspondence",
    finance: "Financial Archive",
    emailArchive: "Email Archive",
    search: "Unified Search",
    notifications: "Notifications",
    reports: "Reports",
    faq: "FAQ",
    users: "Users",
    // App shell
    appName: "Smart Archive",
    appSub: "Archive Management System",
    system: "System",
    // Notifications panel
    alerts: "Notifications",
    markAllRead: "Mark all as read",
    noNotifications: "No notifications",
    showAll: "View all",
    // Login
    welcome: "Welcome",
    smartSystem: "Smart Archive System",
    loginTitle: "Sign In",
    employee: "Employee",
    admin: "Admin",
    adminUsername: "Username",
    adminPassword: "Password",
    emailField: "Email / Username",
    passwordField: "Password",
    loginBtn: "Sign In",
    loggingIn: "Signing in…",
    fillFields: "Please fill all fields",
    errorOccurred: "An error occurred, please try again",
    quickAdd: "Add new",
    logout: "Logout",
    // Dashboard
    dashboardSub: "Overview of all your projects",
    docsAndRecords: "Documents & Records",
    recentProjects: "Recent Projects",
    viewAll: "View all",
    totalProjects: "Total Projects",
    activeProjects: "Active Projects",
    completedProjects: "Completed",
    onHoldProjects: "On Hold",
    totalContracts: "Contracts",
    totalDocuments: "Documents",
    totalMeetings: "Meetings",
    totalLetters: "Letters",
    // Projects page
    newProject: "New Project",
    searchProject: "Search projects...",
    allStatuses: "All Statuses",
    noProjects: "No Projects",
    noProjectsSub: "Start by adding your first project",
    addProject: "Add Project",
    edit: "Edit",
    delete: "Delete",
    deleteProject: "Delete Project",
    deleteProjectMsg: "Are you sure you want to delete this project? All related data will be deleted.",
    projectCreated: "Project created successfully",
    projectCreateFail: "Failed to create project",
    projectUpdated: "Project updated",
    projectUpdateFail: "Failed to update",
    projectDeleted: "Project deleted",
    projectDeleteFail: "Failed to delete",
    saving: "Saving...",
    createProjectBtn: "Create Project",
    saveEdits: "Save Changes",
    projectNameLabel: "Project Name *",
    projectNamePlaceholder: "e.g. Central Business Tower",
    descLabel: "Description",
    descPlaceholder: "Brief project description...",
    clientLabel: "Client *",
    clientPlaceholder: "Client or organization name",
    statusLabel: "Status",
    progressLabel: "Progress",
    startDateLabel: "Start Date *",
    endDateLabel: "End Date",
    budgetLabel: "Budget (SAR)",
    locationLabel: "Location",
    locationPlaceholder: "City, District",
    mapsLabel: "Google Maps Link",
    // Contracts page
    contractsSub: "All contracts across projects",
    addBtn: "Add",
    searchContract: "Search contracts...",
    noContracts: "No Contracts",
    noContractsSub: "Add the first contract using the button above",
    addContract: "Add Contract",
    contractAdding: "Adding...",
    addContractBtn: "Add Contract",
    projectField: "Project *",
    chooseProject: "Choose project",
    contractTitle: "Contract Title *",
    contractTitlePlaceholder: "Contract title",
    contractParty: "Other Party *",
    contractPartyPlaceholder: "Company or contractor name",
    contractValue: "Contract Value (SAR)",
    notes: "Notes",
    // Contractors page
    contractorsSub: "All contractors across projects",
    searchContractor: "Search contractors...",
    noContractors: "No Contractors",
    noContractorsSub: "Add the first contractor using the button above",
    addContractor: "Add Contractor",
    contractorName: "Name *",
    contractorNamePh: "Contractor name",
    specialty: "Specialty *",
    specialtyPh: "Civil engineer, electrician...",
    phone: "Phone",
    email: "Email",
    contractorAdding: "Adding...",
    addContractorBtn: "Add Contractor",
    active: "Active",
    inactive: "Inactive",
    editRating: "Edit Rating",
    ratePerf: "Rate Performance",
    average: "Average",
    workQuality: "Work Quality",
    scheduleCompliance: "Schedule Compliance",
    safetyStandards: "Safety Standards",
    executionSpeed: "Execution Speed",
    saveRating: "Save Rating",
    cancelBtn: "Cancel",
    // Meetings page
    meetingsSub: "All meetings across projects",
    searchMeeting: "Search meetings...",
    noMeetings: "No Meetings",
    noMeetingsSub: "Add the first meeting using the button above",
    addMeeting: "Add Meeting",
    meetingTitle: "Meeting Subject *",
    meetingTitlePh: "Meeting subject",
    meetingDate: "Date *",
    meetingLocation: "Location",
    meetingLocationPh: "Conference room...",
    agenda: "Agenda",
    agendaPrefix: "Agenda:",
    attendees: "attendees",
    meetingAdding: "Adding...",
    addMeetingBtn: "Add Meeting",
    // Letters page
    lettersSub: "All outgoing and incoming letters",
    searchLetter: "Search letters...",
    noLetters: "No Letters",
    noLettersSub: "Add the first letter using the button above",
    addLetter: "Add Letter",
    letterSubject: "Subject *",
    letterSubjectPh: "Letter subject",
    direction: "Direction",
    outgoing: "Outgoing",
    incoming: "Incoming",
    from: "From *",
    fromPh: "Sender",
    to: "To *",
    toPh: "Recipient",
    refNum: "Reference Number",
    autoRefNote: "A reference number will be auto-generated on save",
    letterAdding: "Adding...",
    addLetterBtn: "Add Letter",
    received: "Received",
    sent: "Sent",
    notSent: "Not Sent",
    // Finance page
    financeSub: "Revenue, expenses and financial reminders",
    totalIncome: "Total Revenue",
    totalExpense: "Total Expenses",
    netBalance: "Net Balance",
    surplus: "Surplus",
    deficit: "Deficit",
    reminders30: "Reminders in 30 Days",
    reminder: "Reminder",
    all: "All",
    income: "Revenue",
    expense: "Expenses",
    noFinance: "No Records",
    noFinanceSub: "Add the first financial record",
    financeAdded: "Financial record added",
    financeAddFail: "Failed to add",
    financeUpdated: "Record updated",
    financeUpdateFail: "Failed to update",
    financeDeleted: "Record deleted",
    financeDeleteFail: "Failed to delete",
    deleteFinance: "Delete Financial Record",
    deleteFinanceMsg: "Are you sure you want to delete this financial record?",
    addFinance: "Add Financial Record",
    editFinance: "Edit Financial Record",
    incomeBtn: "Revenue +",
    expenseBtn: "Expense −",
    financeTitle: "Title *",
    financeTitlePh: "e.g. Central Tower project payment",
    amount: "Amount (SAR) *",
    category: "Category",
    reminderDate: "Reminder Date",
    addFinanceBtn: "Add Record",
    // Search page
    searchSub: "Search all projects and data",
    searchPlaceholder: "Search anything...",
    searchPrompt: "Type to search projects, contractors, contracts...",
    results: "result(s)",
    noResults: "No results found",
    // Reports page
    reportsSub: "Detailed reports per project",
    weekly: "Weekly",
    monthly: "Monthly",
    exportPDF: "Export as PDF",
    noReports: "No projects to report on",
    progress: "Progress",
    // Users page
    usersSub: "Manage accounts, permissions and audit log",
    usersTab: "Users",
    auditTab: "Audit Log",
    adminOnly: "This page is for administrators only",
    noAudit: "No audit logs yet",
    changeRole: "Change",
    save: "Save",
  },
} as const;

export type TKey = keyof typeof T.ar;

interface LangCtx {
  lang: Lang;
  dir: "rtl" | "ltr";
  t: (k: TKey) => string;
  toggle: () => void;
}

const Ctx = createContext<LangCtx>({
  lang: "ar", dir: "rtl",
  t: (k) => T.ar[k],
  toggle: () => {},
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("ar");
  const dir: "rtl" | "ltr" = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang, dir]);

  const t = useCallback((k: TKey): string => T[lang][k], [lang]);

  const toggle = useCallback(() => {
    setLang(l => {
      const next = l === "ar" ? "en" : "ar";
      // Trigger Google Translate for dynamic content
      setTimeout(() => {
        (window as any).__gtSwitchLang?.(next);
      }, 100);
      return next;
    });
  }, []);

  return <Ctx.Provider value={{ lang, dir, t, toggle }}>{children}</Ctx.Provider>;
}

export const useLanguage = () => useContext(Ctx);
